### ISSUE TITLE
Create a zip release?

### ISSUE THREAD

**Issue by coolaj86** [QbeRoot/shinehax-gc#1]
Hello!

Would you mind uploading a zip release to Github Releases?

In fact, since you include the binary GCI alongside the source code that would be as easy as running these commands:

```bash
git clone git@github.com:QbeRoot/shinehax-gc.git
pushd shinehax-gc
git tag v1.0.0
git push --tags
```

That will create a release for the source code as v1.0.0, and it will happen to include the binary file as well.

## Rationale

I'm creating a tutorial on how to use GameSave hacks and this is the only one that has source available on Github, but no download on the releases page. It's a small difference but... you'd be surprised how any small difference in a process can confuse people to a great extent.

Thanks for the consideration.

**Comment by coolaj86** [comment]
One other thing that's different is that you have your file named by the hack rather than by the model number.

I believe that this would be `GMSP.gci`?

**Comment by QbeRoot** [comment]
Hi!

The release is up now, thanks for the suggestion and sorry for the delay.
